### ISSUE TITLE
Termina el ejercicio!

### ISSUE THREAD

**Issue by oneeyedman** [Adalab/f-m3-evaluacion-intermedia-irisparedes#1]
Buen trabajo @irisparedes  !

Algunas pistas para acabarlo:
- [x] Termina de añadir los elementos finales de la tarjeta de cada Pokemon: un div o article que la englobe (mira el error que tienes en consola) y una imagen para mostrar el Pokemon
- [x] Usa el id de cada pokemon para el key de react cuando mapeas y creas un listado de componentes
- [x] Añade estilos (un archivo sass o css por componente)
- [x] Usa propTypes para comprobar el tipo de dato de las props
- [x] Revisa los metadatos en index.html (lang, title...)
- [x] Limpia e indenta el código
- [x] Publica en Github Pages
- [x] Elimina archivos sin usary sus referencias
Si tienes cualquier duda, avisa!

Al turrón

**Comment by irisparedes** [comment]
Done! Anyway, I'm waiting for something to be corrected. Thank you!

**Comment by oneeyedman** [comment]
Buen trabajo, @irisparedes!

PD: No me cierres las issues y deja que las cierre quien las pone
